<?php
/**
 * @license See the file LICENSE for copying permission
 */

declare(strict_types=1);

namespace Fig\Website;

class Psr
{
    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $source;

    /**
     * @var string
     */
    private $dest;

    /**
     * @var PsrExtra{}
     */
    private $related;

    public function __construct(string $title, string $source, string $dest, array $related = [])
    {
        $this->title   = $title;
        $this->source  = $source;
        $this->dest    = $dest;
        $this->related = $related;
    }

    public static function fromSource(string $source): self
    {
        $match = preg_match('/(psr-\d+)(?:-(\w+(?:-\w+)*)+)?(?:-(meta|example))?\.md$/i', $source, $matches);

        if (! $match) {
            throw new \InvalidArgumentException(sprintf("Source doesn't match pattern: %s", $source));
        }

        $psrNumber = strtolower($matches[1]);
        $shortName = $matches[2] ?? '';
        $type      = $matches[3] ?? 'psr';

        $file = fopen($source, 'r');
        $title = rtrim(ltrim(fgets($file), '# '));
        fclose($file);

        if (strpos($title, $psrNumber) !== 0) {
            $title = $psrNumber . ': ' . $title;
        }

        $dest = PSR_DIR . $psrNumber . '-' . $shortName . '.twig';
        $dest = strtolower($dest);

        $related = [];

        if ($type !== 'psr') {
            $related[] = PsrExtra::fromSource($source);
        }

        return new static($title, $source, $dest, $related);
    }

    public function __toString(): string
    {
        return $this->dest;
    }

    public function alreadyExists(): bool
    {
        return file_exists($this->dest);
    }

    public function writeToDest(): void
    {
        file_put_contents($this->dest, $this->createContent());
    }

    private function createContent(): string
    {
        $relSource = str_replace(INCLUDES_DIR, '', $this->source);

        $content   = <<<CONTENT
---
"# This file is automatically generated by `build.php`.
title: $this->title
markdown_source: $relSource
additional:
 - name: PSR-2: Coding Style Guide
   path: /pages/psr/psr-2
 - name: PSR-2 Meta Document
---

{{ parent() }}

CONTENT;

        return $content;
    }
}
